### ISSUE TITLE
bluss contact form

### ISSUE THREAD

**Issue by bluss** [bluss/rustfaq#1]
You can find me as `bluss` or `bluss2` (mobile) on [mozilla's irc channels](https://www.rust-lang.org/en-US/community.html), including #rust, #rust-libs #rust-sci and many more of them.

**Comment by pmarks** [comment]
Hi @bluss, I tried to find you on IRC a couple times without luck. We (@10xgenomics) are looking to create high-quality pure Rust ports of some dimensionality reduction (SVD/PCA, t-SNE, UMAP) and clustering (k-medioids, Louvain, etc) algorithms. These would be MIT licensed and hopefully integrate nicely with the emerging #rust-sci ecosystem. Wondering if you or someone you know might be interested in tackling some of these for us on a contract basis. Please email if you'd like to discuss in more detail. Thanks!
